version: 2

jobs:
  compile:
    docker:
    - image: mcelayir/sbt-jdk:latest
    steps:
    - restore_cache:
        key: sbt-cache
    - checkout
    - run:
        name: Clean
        command: sbt clean
    - run:
        name: Compile
        command: sbt compile
    - save_cache:
        key: sbt-cache
        paths:
        - "~/.ivy2/cache"
        - "~/.sbt"
        - "~/.m2"
  test:
    docker:
    - image: mcelayir/sbt-jdk:latest
    steps:
    - restore_cache:
        key: sbt-cache
    - checkout
    - run:
        name: Test
        command: sbt test
  publish:
    docker:
    - image: mcelayir/sbt-jdk:latest
    steps:
    - setup_remote_docker
    - run:
        name: Docker login
        command: docker login -u $DOCKER_USER -p $DOCKER_PASS
    - restore_cache:
        key: sbt-cache
    - checkout
    - run:
        name: Publish
        command: sbt docker:publish

workflows:
  version: 2
  build-and-test-and-deploy:
    jobs:
    - compile
    - test:
        requires:
        - compile
    - publish:
        requires:
        - test